FROM rabbitmq:3-management-alpine
LABEL maintainer="Charlie Lewis <clewis@iqt.org>" \
      vent="" \
      vent.name="rabbitmq" \
      vent.groups="core,messages,syslog" \
      vent.section="cyberreboot:vent:/vent/core/rabbitmq:master:HEAD" \
      vent.repo="https://github.com/cyberreboot/vent" \
      vent.type="repository"
