FROM rabbitmq:3-management
MAINTAINER Charlie Lewis <clewis@iqt.org>
LABEL vent="" \
      vent.name="rabbitmq" \
      vent.groups="core,messages,syslog" \
      vent.section="cyberreboot:vent:/vent/core/rabbitmq:master:HEAD" \
      vent.repo="https://github.com/cyberreboot/vent" \
      vent.type="repository"
