sudo: required
dist: trusty
group: edge

services:
  - docker
  - redis
  - elasticsearch
language: python
python:
  - "3.6"
before_script:
  - sleep 10
  - echo -e "https://github.com/cyberreboot/vent:\n  rabbitmq:" >> ~/.vent_startup.yml
script:
  - make test
  - bash <(curl -s https://codecov.io/bash)
before_install:
  - sudo apt-get update
  - sudo apt-get install docker-ce
