sudo: required
dist: trusty
group: edge

services:
  - docker
  - redis
  - elasticsearch
language: python
cache: pip
python:
  - "3.6"
before_script:
  - sleep 10
  - echo -e "https://github.com/cyberreboot/vent:\n  redis:" >> ~/.vent_startup.yml
before_install:
  - sudo apt-get update
  - sudo apt-get install docker-ce
jobs:
  include:
  - stage: test
    script: make test-menu && bash <(curl -s https://codecov.io/bash)
  - script: make test-unit && bash <(curl -s https://codecov.io/bash)
  - script: make test-plugins && bash <(curl -s https://codecov.io/bash)
