sudo: required
dist: trusty
group: edge

services:
  - docker
  - redis
  - elasticsearch
language: python
cache: pip
python:
  - "3.6"
before_script:
  - sleep 10
  - echo -e "https://github.com/cyberreboot/vent:\n  rabbitmq:" >> ~/.vent_startup.yml
before_install:
  - sudo apt-get update
  - sudo apt-get install docker-ce
jobs:
  include:
  - stage: test
    script: make test-menu
  - script: make test-unit
  - script: make test-plugins
  - stage: coverage
    script: bash <(curl -s https://codecov.io/bash)
