#!/bin/sh

if [ ! -f "/var/lib/boot2docker/bootlocal.sh" ]; then
	sudo /usr/local/etc/init.d/openssh stop
	pgrep /usr/local/sbin/sshd | sudo xargs kill -9
	mv /data/bootlocal.sh /var/lib/boot2docker/bootlocal.sh
	chmod +x /var/lib/boot2docker/bootlocal.sh
	mv /data/profile /var/lib/boot2docker/profile
	docker load -i /data/management/vent-management.tar
	echo $'Match User docker\n\tAllowTCPForwarding no\n\tX11Forwarding no\n\tForceCommand /data/wrapper.sh' >> /usr/local/etc/ssh/sshd_config
	reboot
else
	exists=$(docker ps -aq --filter name=vent-management | wc -l)
    if [[ "$exists" == *"1" ]]; then
		docker start vent-management
	else
		docker run --name vent-management -d -v /mnt/sda1/var/lib/boot2docker/tls:/certs -v /var/run/docker.sock:/var/run/docker.sock -v /tmp:/tmp vent-management
	fi
fi
