#!/bin/sh

if [ ! -f "/var/lib/boot2docker/bootlocal.sh" ]; then
	sudo /usr/local/etc/init.d/openssh stop
	pgrep /usr/local/sbin/sshd | sudo xargs kill -9
	mv /data/bootlocal.sh /var/lib/boot2docker/bootlocal.sh
	chmod +x /var/lib/boot2docker/bootlocal.sh
	mv /data/profile /var/lib/boot2docker/profile
	docker load -i /data/management/vent-management.tar
	cd /data/plugins && find . -type d -exec sh -c '(cd {} && [ -f Dockerfile ] && docker build -t $(echo {} | sed 's%^.\/%%') .)' ';'
	reboot
fi
