FROM alpine:3.4
MAINTAINER Charlie Lewis <clewis@iqt.org>

RUN apk add --update \
    libmagic \
    python \
    py-pip \
    && rm -rf /var/cache/apk/*

ADD . /vent
WORKDIR /vent
RUN pip install -r tests/requirements.txt
CMD py.test -v --cov=. --cov-report term-missing && cat .coverage
