FROM elasticsearch:2-alpine
FROM rabbitmq:3-management
FROM redis:alpine
FROM ubuntu:latest
LABEL maintainer="Charlie Lewis <clewis@iqt.org>"

RUN apt-get update && apt-get install -y \
    apt-transport-https \
    ca-certificates \
    curl \
    git \
    make \
    python \
    python-pip \
    software-properties-common

RUN curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -
RUN add-apt-repository \
    "deb [arch=amd64] https://download.docker.com/linux/ubuntu \
    $(lsb_release -cs) \
    stable"

RUN apt-get update && apt-get install -y docker-ce

ADD . /vent
WORKDIR /vent
RUN pip install -r tests/requirements.txt
RUN python2.7 setup.py install

ENTRYPOINT ["pytest"]
CMD ["-l", "-s", "-v", "--cov=.", "-k", "'not vendor'", "--cov-report", "term-missing"]
