FROM redis:alpine
MAINTAINER Charlie Lewis <clewis@iqt.org>
LABEL vent="" \
      vent.name="redis" \
      vent.groups="core" \
      vent.section="cyberreboot:vent:/vent/core/redis:master:HEAD" \
      vent.repo="https://github.com/cyberreboot/vent" \
      vent.type="repository"
