#!/bin/bash

echo "Assumes you have docker-machine installed and vent is connected to it."
if [ "$#" -ne 1 ]; then
    HOST="vent"
else
    HOST=$1
fi

echo "Note: this does not copy files recursively..."
for file in `ls *` ; do
    docker-machine scp $file $HOST:/tmp/.${file}.tmp
    docker-machine ssh $HOST "mv /tmp/.${file}.tmp /files/$file"
done
